/**
 * Build the distributable artifacts and check they are actually well formed (scope.md 13).
 *
 *   node scripts/package.mjs [--browser=chrome|firefox|both]
 *
 * Until now nothing built either one: both e2e harnesses load an unpacked directory, so a
 * packaging step that produced a corrupt or empty archive would have gone unnoticed until
 * someone tried to install it. This produces them and then reads them back -- the same
 * reasoning as `tools/publish_bundle.py`, which re-downloads and re-hashes what it uploaded
 * rather than assuming the upload worked.
 *
 * The signing key is generated by Chrome on first run and kept in `artifacts/packages/`,
 * which is gitignored. It is the extension's identity: losing it means a new extension id.
 *
 * What this does NOT do is produce an AMO-signed `.xpi`. That needs the account's API
 * credentials, so the Firefox artifact here is the unsigned archive `web-ext sign` would
 * upload. See extension/README.md for what remains manual.
 */

import { execFileSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  renameSync,
  rmSync,
  statSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { argv, exit } from "node:process";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const repo = resolve(root, "..");
const out = join(repo, "artifacts", "packages");

const value = (name, fallback) => {
  const hit = argv.find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.split("=").slice(1).join("=") : fallback;
};
const which = value("browser", "both");

const manifest = JSON.parse(readFileSync(join(root, "src", "assets", "manifest.json"), "utf-8"));
const VERSION = manifest.version;

const results = [];
const check = (name, ok, detail = "") => {
  results.push({ name, ok, detail });
  console.log(`  ${ok ? "PASS" : "FAIL"}  ${name}${detail ? ` — ${detail}` : ""}`);
};

const mb = (bytes) => `${(bytes / 1e6).toFixed(2)} MB`;

/**
 * Run a local binary from node_modules/.bin. `shell: true` because on Windows the entry
 * point is a .cmd, which execFile cannot spawn directly (EINVAL), and quoting because the
 * shell then re-parses the arguments.
 */
function npx(args, options = {}) {
  const quoted = args.map((a) => (/[\s"]/.test(a) ? `"${a}"` : a));
  return execFileSync("npx", quoted, { shell: true, cwd: root, ...options });
}

/**
 * The names in a zip's central directory, which is the only place they can be read
 * reliably: web-ext writes entries with data descriptors, so the local headers carry a
 * compressed size of zero and cannot be walked sequentially at all.
 *
 * `from` is where the archive begins inside the buffer, which is non-zero for a .crx --
 * central-directory offsets are relative to the start of the zip, not the file.
 */
function zipEntries(buffer, from = 0) {
  // End of central directory: scan back for its signature, past any trailing comment.
  let eocd = -1;
  for (let i = buffer.length - 22; i >= from; i--) {
    if (buffer.readUInt32LE(i) === 0x06054b50) {
      eocd = i;
      break;
    }
  }
  if (eocd < 0) return [];

  const total = buffer.readUInt16LE(eocd + 10);
  let at = from + buffer.readUInt32LE(eocd + 16);
  const names = [];
  for (let n = 0; n < total && at + 46 <= buffer.length; n++) {
    if (buffer.readUInt32LE(at) !== 0x02014b50) break;
    const nameLength = buffer.readUInt16LE(at + 28);
    const extraLength = buffer.readUInt16LE(at + 30);
    const commentLength = buffer.readUInt16LE(at + 32);
    names.push(buffer.subarray(at + 46, at + 46 + nameLength).toString("utf-8"));
    at += 46 + nameLength + extraLength + commentLength;
  }
  return names;
}

/* ------------------------------------------------------------------------- chrome */

async function packChrome() {
  const dist = join(root, "dist", "chrome");
  if (!existsSync(join(dist, "manifest.json"))) {
    console.error(`no build at ${dist} — run: node scripts/build.mjs --browser=chrome`);
    return false;
  }

  const { chromium } = await import("playwright");
  const key = join(out, "chrome-key.pem");
  const args = [`--pack-extension=${dist}`];
  if (existsSync(key)) args.push(`--pack-extension-key=${key}`);

  // Chrome writes <dist>.crx and, when it generated one, <dist>.pem beside the directory.
  execFileSync(chromium.executablePath(), args, { stdio: "pipe" });

  const producedCrx = `${dist}.crx`;
  const producedKey = `${dist}.pem`;
  if (!existsSync(producedCrx)) {
    check("chrome produces a .crx", false, "no file was written");
    return false;
  }
  if (existsSync(producedKey)) {
    renameSync(producedKey, key);
    console.log(`  new signing key -> ${key} (keep it: it is the extension id)`);
  }

  const crx = join(out, `slop-marker-${VERSION}.crx`);
  rmSync(crx, { force: true });
  renameSync(producedCrx, crx);
  check("chrome produces a .crx", true, `${crx} (${mb(statSync(crx).size)})`);

  // CRX3: "Cr24", version 3, header length, protobuf header, then the zip.
  const bytes = readFileSync(crx);
  const magic = bytes.subarray(0, 4).toString("latin1");
  const format = bytes.readUInt32LE(4);
  check("the .crx carries a CRX3 header", magic === "Cr24" && format === 3, `${magic} v${format}`);

  const headerLength = bytes.readUInt32LE(8);
  const zipAt = 12 + headerLength;
  check(
    "the .crx is signed, and the payload starts where the header ends",
    headerLength > 0 && bytes.readUInt32LE(zipAt) === 0x04034b50,
    `${headerLength} byte header`,
  );

  const entries = zipEntries(bytes, zipAt);
  const wanted = ["manifest.json", "content.js", "router-chrome.js", "worker.js", "host.html"];
  const missing = wanted.filter((f) => !entries.includes(f));
  check(
    "the .crx contains the extension",
    missing.length === 0,
    missing.length === 0 ? `${entries.length} entries` : `missing ${missing.join(", ")}`,
  );
  return missing.length === 0;
}

/* ------------------------------------------------------------------------ firefox */

async function packFirefox() {
  const dist = join(root, "dist", "firefox");
  if (!existsSync(join(dist, "manifest.json"))) {
    console.error(`no build at ${dist} — run: node scripts/build.mjs --browser=firefox`);
    return false;
  }

  npx(["web-ext", "build", "--source-dir", dist, "--artifacts-dir", out, "--overwrite-dest"], {
    stdio: "pipe",
  });

  // web-ext derives the archive name from the manifest, sanitised in a way that has
  // changed between versions -- so take whatever .zip it just wrote rather than guessing.
  const built = readdirSync(out)
    .filter((f) => f.endsWith(".zip"))
    .map((f) => join(out, f))
    .sort((a, b) => statSync(b).mtimeMs - statSync(a).mtimeMs)[0];
  if (built === undefined) {
    check("web-ext builds an archive", false, `nothing was written to ${out}`);
    return false;
  }
  const xpi = join(out, `slop-marker-${VERSION}.xpi`);
  rmSync(xpi, { force: true });
  renameSync(built, xpi);
  check("web-ext builds an .xpi", true, `${xpi} (${mb(statSync(xpi).size)})`);

  const bytes = readFileSync(xpi);
  check("the .xpi is a zip", bytes.readUInt32LE(0) === 0x04034b50, bytes.subarray(0, 2).toString());

  const entries = zipEntries(bytes);
  const wanted = ["manifest.json", "content.js", "router-firefox.js", "worker.js"];
  const missing = wanted.filter((f) => !entries.includes(f));
  check(
    "the .xpi contains the extension",
    missing.length === 0,
    missing.length === 0 ? `${entries.length} entries` : `missing ${missing.join(", ")}`,
  );

  // Lint the archive itself rather than the directory it came from.
  let lintOk = true;
  let lintDetail = "0 errors";
  try {
    npx(["web-ext", "lint", "--source-dir", dist, "--output", "json"], { stdio: "pipe" });
  } catch (err) {
    const report = String(err.stdout ?? "");
    try {
      const parsed = JSON.parse(report.slice(report.indexOf("{")));
      lintOk = parsed.errors.length === 0;
      lintDetail = `${parsed.errors.length} errors, ${parsed.warnings.length} warnings`;
    } catch {
      lintOk = false;
      lintDetail = "web-ext lint could not be parsed";
    }
  }
  check("web-ext lint reports no errors", lintOk, lintDetail);

  console.log(
    "\n  NOT signed. `web-ext sign --channel=unlisted` needs AMO API credentials;\n" +
      "  this archive is what it would upload.",
  );
  return missing.length === 0 && lintOk;
}

/* ---------------------------------------------------------------------------- run */

mkdirSync(out, { recursive: true });
console.log(`packaging v${VERSION} -> ${out}\n`);

if (which === "chrome" || which === "both") {
  console.log("chrome:");
  await packChrome();
}
if (which === "firefox" || which === "both") {
  console.log(`${which === "both" ? "\n" : ""}firefox:`);
  await packFirefox();
}

const failed = results.filter((r) => !r.ok);
console.log(`\n${results.length - failed.length}/${results.length} checks passed`);
exit(failed.length === 0 ? 0 : 1);
