/**
 * GENERATED by tools/sync_extension_assets.py -- do not edit.
 *
 * Regenerate after a model refresh:
 *   uv run python tools/sync_extension_assets.py --bundle artifacts/bundles/<version>
 *
 * scope.md 4.7: a new model must not require an extension code change. Everything
 * model-specific lives here and in the bundled assets, and all of it is generated.
 */

/** Bundle this extension release expects. Keys the score cache (scope.md 11). */
export const MODEL_VERSION = "mb-base-0.2.0-dev";

/**
 * Where the bundle is served from (scope.md 6.4). Files are fetched as
 * `${MODEL_BASE_URL}/${MODEL_VERSION}/${file}`, which is the layout GitHub Releases
 * gives you for free when the release tag is the model version.
 *
 * `scripts/build.mjs --model-base-url=<url>` overrides it at bundle time without editing
 * this file, which is how e2e/run.mjs points a build at its own throwaway local host.
 */
declare const MODEL_HOST_OVERRIDE: string;
export const MODEL_BASE_URL: string = MODEL_HOST_OVERRIDE || "https://github.com/OWNER/REPO/releases/download";

/**
 * What is actually downloaded. Only the weights: the tokenizer and the calibration
 * constants ship inside the extension (scope.md 6.3 bundles the tokenizer so browser
 * tokenization cannot drift), and config.json is training metadata the runtime never reads.
 * So first run fetches one 137 MB file, not a 140 MB directory.
 */
export const BUNDLE_FILES = [
  "model.onnx"
] as const;

/**
 * The checksums this extension release was built against, copied from the bundle. Downloads
 * are verified against THIS, not against a SHA256SUMS fetched alongside them -- otherwise a
 * tampered upload would simply ship its own matching checksums.
 */
export const SHIPPED_SHA256SUMS = "fe5b32fe0117f9a59a3c5c952b699c087263cfb43b1906ffb4ed42bdf6ed50b8  calibration.json\na2a483f6c8893e8d096920453b224ca7e029e6caac59d68331f63b6bf196b6b3  config.json\n42e850ac70f2df942d3e36fbc5a702dd5eb4a352c105d29732f7562fca0fb22c  model.onnx\n6c8aaa9a542084f2457eab775d4eeb51f92a70c0fd9de28d5edb0ddec3c08d30  tokenizer.json\nc5a7dfd44d93c5d7ed9b2ddcd7a6018e935ec7d53f1de45910ea9868e0ff1c17  tokenizer_config.json\n";

/** Verbatim calibration.json from the bundle. Parsed by parseCalibration, never by hand. */
export const SHIPPED_CALIBRATION_JSON = "{\n  \"schema_version\": 1,\n  \"version\": \"mb-base-0.2.0-dev\",\n  \"temperature\": 0.731,\n  \"t_on\": 0.8397,\n  \"t_off\": 0.742,\n  \"min_words\": 40,\n  \"max_length\": 512,\n  \"aggregate\": {\n    \"length_penalty_words\": 80,\n    \"run_min_words\": 150,\n    \"doc_prior_min_fraction\": 0.2,\n    \"doc_prior_bump_logodds\": 0.25\n  }\n}\n";
