"""Copy the tracked files of a bundle release into the extension, and generate its config.

The root README promises this script. Two small files from each bundle release are tracked
inside extension/src/assets/ -- the tokenizer, so browser tokenization cannot drift, and
calibration.json + SHA256SUMS, which the extension verifies downloads against. They are
copied in from a bundle release by this script, never hand-edited.

    uv run python tools/sync_extension_assets.py --bundle artifacts/bundles/mb-base-0.2.0-dev

It also writes extension/src/shared/bundle-config.ts. That file is generated, not authored:
it carries the model version, the expected checksums and the calibration constants, so that
scope.md 4.7's promise holds -- a model refresh is a new bundle plus a re-run of this
script, and no TypeScript is edited by hand.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ASSETS = REPO / "extension" / "src" / "assets"
CONFIG_TS = REPO / "extension" / "src" / "shared" / "bundle-config.ts"

# Copied into the extension. model.onnx and config.json are not: the first is 137 MB and is
# downloaded, the second is training metadata the runtime never reads.
TRACKED = ("tokenizer.json", "tokenizer_config.json", "calibration.json", "SHA256SUMS")

DEFAULT_BASE_URL = "https://github.com/OWNER/REPO/releases/download"

TEMPLATE = '''/**
 * GENERATED by tools/sync_extension_assets.py -- do not edit.
 *
 * Regenerate after a model refresh:
 *   uv run python tools/sync_extension_assets.py --bundle artifacts/bundles/<version>
 *
 * scope.md 4.7: a new model must not require an extension code change. Everything
 * model-specific lives here and in the bundled assets, and all of it is generated.
 */

/** Bundle this extension release expects. Keys the score cache (scope.md 11). */
export const MODEL_VERSION = {version};

/**
 * Where the bundle is served from (scope.md 6.4). Files are fetched as
 * `${{MODEL_BASE_URL}}/${{MODEL_VERSION}}/${{file}}`, which is the layout GitHub Releases
 * gives you for free when the release tag is the model version.
 */
export const MODEL_BASE_URL = {base_url};

/**
 * What is actually downloaded. Only the weights: the tokenizer and the calibration
 * constants ship inside the extension (scope.md 6.3 bundles the tokenizer so browser
 * tokenization cannot drift), and config.json is training metadata the runtime never reads.
 * So first run fetches one 137 MB file, not a 140 MB directory.
 */
export const BUNDLE_FILES = {bundle_files} as const;

/**
 * The checksums this extension release was built against, copied from the bundle. Downloads
 * are verified against THIS, not against a SHA256SUMS fetched alongside them -- otherwise a
 * tampered upload would simply ship its own matching checksums.
 */
export const SHIPPED_SHA256SUMS = {sha256sums};

/** Verbatim calibration.json from the bundle. Parsed by parseCalibration, never by hand. */
export const SHIPPED_CALIBRATION_JSON = {calibration};
'''


def ts_string(text: str) -> str:
    """A TypeScript string literal. json.dumps produces valid TS for any str."""
    return json.dumps(text)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--bundle", type=Path, required=True)
    ap.add_argument(
        "--base-url",
        default=None,
        help=f"model host base URL (default: keep existing, else {DEFAULT_BASE_URL})",
    )
    args = ap.parse_args()

    bundle: Path = args.bundle.resolve()
    missing = [f for f in (*TRACKED, "model.onnx") if not (bundle / f).is_file()]
    if missing:
        print(f"bundle is incomplete, missing: {', '.join(missing)}", file=sys.stderr)
        return 1

    sys.path.insert(0, str(REPO / "training" / "src"))
    from slopmarker.export.bundle import verify_sha256sums

    problems = verify_sha256sums(bundle)
    if problems:
        for p in problems:
            print(f"  CHECKSUM: {p}", file=sys.stderr)
        print("refusing to sync an unverified bundle", file=sys.stderr)
        return 1

    ASSETS.mkdir(parents=True, exist_ok=True)
    for name in TRACKED:
        shutil.copy2(bundle / name, ASSETS / name)
        print(f"  {name} -> extension/src/assets/")

    calibration_text = (bundle / "calibration.json").read_text(encoding="utf-8")
    calibration = json.loads(calibration_text)
    sha_text = (bundle / "SHA256SUMS").read_text(encoding="utf-8")

    base_url = args.base_url
    if base_url is None:
        # Keep whatever the previous generation used, so re-syncing a new model does not
        # silently reset the host back to the placeholder.
        base_url = DEFAULT_BASE_URL
        if CONFIG_TS.is_file():
            for line in CONFIG_TS.read_text(encoding="utf-8").splitlines():
                if line.startswith("export const MODEL_BASE_URL = "):
                    base_url = json.loads(line.split("=", 1)[1].strip().rstrip(";"))
                    break

    bundle_files = ["model.onnx"]

    CONFIG_TS.write_text(
        TEMPLATE.format(
            version=ts_string(calibration["version"]),
            base_url=ts_string(base_url),
            bundle_files=json.dumps(sorted(bundle_files), indent=2),
            sha256sums=ts_string(sha_text),
            calibration=ts_string(calibration_text),
        ),
        encoding="utf-8",
        newline="\n",
    )
    print(f"  bundle-config.ts -> version {calibration['version']}, host {base_url}")
    if "OWNER/REPO" in base_url:
        print("\n  NOTE: model host is still the placeholder. Set it with --base-url before release.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
